run-name: Launch Testing

on: [push]

env:
  appNamePrefix: 'shoppingapp1'

jobs:
##################### Launch Load Testing #####################
  Load_Testing:
    runs-on: [self-hosted, dotnet]
    env:
      loadTestConfigFile: 'test/ShoppingApp.LoadTests/ShoppingApp.WebUI.DefaultTests.yaml'
      webUiCaUrl: 'ctap-shoppingapp1-ui-sa1--v0-0-1-ci-23.ashypebble-eedc1eec.francecentral.azurecontainerapps.io'
      # Staging 'sa1, sa2 sa3, ...'
      # s - staging a - advanced => sa
      nameSuffix: 'sa1'
    steps:
      - uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Load Testing
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: ${{ env.loadTestConfigFile }}
          loadTestResource: 'lt-${{ env.appNamePrefix }}-${{ env.nameSuffix }}'
          resourceGroup: 'rg-${{ env.appNamePrefix }}-${{ env.nameSuffix }}'
          env: |
            [
              {
                "name": "webUIUrl",
                "value": "${{ env.webUiCaUrl }}"
              }
            ]